### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by 37Rb** [chnejohnson/vue-dapp#64]
I installed vue with `npm init vue@latest` and then did `npm i ethers vue-dapp` but as soon as I add `import { VueDapp } from "vue-dapp";` to my main.ts I get this error in the console:

```
[vite] connecting...
client.ts:53 [vite] connected.
_stream_readable.js:48 Uncaught ReferenceError: global is not defined
    at node_modules/readable-stream/lib/_stream_readable.js (_stream_readable.js:48:21)
    at __require (chunk-7TBCKYSC.js?v=84f0b049:11:50)
    at node_modules/readable-stream/readable-browser.js (readable-browser.js:1:28)
    at __require (chunk-7TBCKYSC.js?v=84f0b049:11:50)
    at node_modules/keccak/lib/api/keccak.js (keccak.js:1:23)
    at __require (chunk-7TBCKYSC.js?v=84f0b049:11:50)
    at node_modules/keccak/lib/api/index.js (index.js:1:22)
    at __require (chunk-7TBCKYSC.js?v=84f0b049:11:50)
    at node_modules/keccak/js.js (js.js:1:18)
    at __require (chunk-7TBCKYSC.js?v=84f0b049:11:50)
```

I'm new to both vue and vue-dapp. Any idea how to fix?

**Comment by 37Rb** [comment]
I should have seen this one. https://github.com/chnejohnson/vue-dapp/issues/28
