### ISSUE TITLE
Type checking error while building but works fine on vscode and demo

### ISSUE THREAD

**Issue by chnejohnson** [chnejohnson/vue-dapp#7]
In the useWallet.ts, if we don't add "any" type in `try...catch(e: any)`,  it will fail to build.

https://github.com/chnejohnson/vue-dapp/blob/0e35ef0ce0bfb213dbc08d4727691ceb35c2a838/src/useWallet.ts#L31

Reproduce: remove ": any" and run `yarn build`

```bash
yarn run v1.22.5
$ rm -rf dist/ && rollup -c

src/index.ts → dist/index.common.js, dist/index.esm.js...
(node:67130) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/***/Desktop/vue-dapp/node_modules/rollup-plugin-typescript2/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
[!] (plugin rpt2) Error: /Users/***/Desktop/vue-dapp/src/useWallet.ts(34,23): semantic error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string | undefined'.
  Type 'unknown' is not assignable to type 'string'.
src/useWallet.ts
Error: /Users/***/Desktop/vue-dapp/src/useWallet.ts(34,23): semantic error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string | undefined'.
  Type 'unknown' is not assignable to type 'string'.
    at error (/Users/***/Desktop/vue-dapp/node_modules/rollup/dist/shared/rollup.js:151:30)
    at throwPluginError (/Users/***/Desktop/vue-dapp/node_modules/rollup/dist/shared/rollup.js:19344:12)
    at Object.error (/Users/***/Desktop/vue-dapp/node_modules/rollup/dist/shared/rollup.js:20013:20)
    at Object.error (/Users/***/Desktop/vue-dapp/node_modules/rollup/dist/shared/rollup.js:19520:38)
    at RollupContext.error (/Users/***/Desktop/vue-dapp/node_modules/rollup-plugin-typescript2/src/rollupcontext.ts:37:18)
    at /Users/***/Desktop/vue-dapp/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:41:11
    at arrayEach (/Users/***/Desktop/vue-dapp/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:516:11)
    at Function._.each [as forEach] (/Users/***/Desktop/vue-dapp/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:9368:14)
    at printDiagnostics (/Users/***/Desktop/vue-dapp/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:9:2)
    at Object.transform (/Users/***/Desktop/vue-dapp/node_modules/rollup-plugin-typescript2/src/index.ts:244:5)

error Command failed with exit code 1.
```

If the type checking of building is right, why my vscode type checking does nothing to warn about this.

**Comment by chnejohnson** [comment]
Deprecated.
